# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="af-magic"
# ZSH_THEME="pure"
# autoload -U promptinit; promptinit
# prompt pure

plugins=(git zsh-syntax-highlighting mvn fasd docker docker-alias fzf vagrant)

source ${ZSH}/oh-my-zsh.sh

# User configuration

export SVN_EDITOR=vim
export LC_CTYPE=en_US.UTF-8
export PMC_AUTH_TOKEN='AK_N3ybTEegw1cjaXZ.nAqtA17mR3snm+mtHTwsK'

alias vim='nvim'
alias view='nvim -R'
alias lc='leetcode'
alias configvim="vim ${HOME}/.config/nvim/init.vim"
alias configzsh="vim ${HOME}/.zshrc"
alias sourcezsh="source ${HOME}/.zshrc"
alias rlog="${HOME}/Documents/rlog.sh rlog"
alias rcp="${HOME}/Documents/rlog.sh rcp"
alias pmc-cli='/usr/local/bin/pmc-cli'
alias bat='bat --theme GitHub'

# Delete old recorded entry if new entry is a duplicate.
setopt HIST_IGNORE_ALL_DUPS
# Do not display a line previously found.
setopt HIST_FIND_NO_DUPS
# Don't write duplicate entries in the history file.
setopt HIST_SAVE_NO_DUPS

# test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# fbr - checkout git branch
fbr() {
  local branches branch
  branches=$(git branch -vv) &&
  branch=$(echo "$branches" | fzf +m) &&
  git checkout $(echo "$branch" | awk '{print $1}' | sed "s/.* //")
}

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="${HOME}/.sdkman"
[[ -s "${HOME}/.sdkman/bin/sdkman-init.sh" ]] && source "${HOME}/.sdkman/bin/sdkman-init.sh"

