ZSH_THEME="lambda-mod"

export ZSH=${HOME}/.oh-my-zsh
export SVN_EDITOR=vim
export LC_CTYPE=en_US.UTF-8
export PMC_AUTH_TOKEN='AK_N3ybTEegw1cjaXZ.nAqtA17mR3snm+mtHTwsK'

alias configvim="vim ${HOME}/.vimrc"
alias configzsh="vim ${HOME}/.zshrc"
alias sourcezsh="source ${HOME}/.zshrc"
alias script="${HOME}/Documents/rlog.sh"
alias pmc-cli="${HOME}/Projects/pmc-cli"

plugins=(git zsh-syntax-highlighting clipboard mvn fasd docker docker-alias fzf vagrant)

source ${ZSH}/oh-my-zsh.sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

